apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: alpine
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: alpine
        image: alpine:latest
        command: ["sh", "-c", "sleep 300"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

